# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuicoes',
            fields=[
                ('distribuicaoID', models.AutoField(primary_key=True, serialize=False)),
                ('distribuicao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estimadores',
            fields=[
                ('estimadorID', models.AutoField(primary_key=True, serialize=False)),
                ('metodo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('parametrosID', models.AutoField(primary_key=True, serialize=False)),
                ('ordem', models.IntegerField()),
                ('tamanho', models.IntegerField()),
                ('forma', models.FloatField()),
                ('escala', models.FloatField()),
                ('posicao', models.FloatField()),
                ('distribuicaoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidroSite.Distribuicoes')),
                ('estimadorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidroSite.Estimadores')),
            ],
        ),
        migrations.CreateModel(
            name='Qualidade',
            fields=[
                ('qualidadeID', models.AutoField(primary_key=True, serialize=False)),
                ('estatisticaTeste', models.FloatField()),
                ('valorP', models.FloatField()),
                ('h', models.IntegerField()),
                ('parametrosID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidroSite.Parametros')),
            ],
        ),
        migrations.CreateModel(
            name='Reducao',
            fields=[
                ('reducaoID', models.AutoField(primary_key=True, serialize=False)),
                ('tipoReducao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SerieExtensa',
            fields=[
                ('serieExtensaID', models.AutoField(primary_key=True, serialize=False)),
                ('dados', models.FloatField()),
                ('reducaoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidroSite.Reducao')),
            ],
        ),
        migrations.CreateModel(
            name='SerieReamostragem',
            fields=[
                ('serieReamostragemID', models.AutoField(primary_key=True, serialize=False)),
                ('tamanho', models.IntegerField()),
                ('ordem', models.IntegerField()),
                ('serieExtensaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidroSite.SerieExtensa')),
            ],
        ),
        migrations.CreateModel(
            name='TesteAderencia',
            fields=[
                ('testeAderenciaID', models.AutoField(primary_key=True, serialize=False)),
                ('tipoTeste', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDados',
            fields=[
                ('tipoDadosID', models.AutoField(primary_key=True, serialize=False)),
                ('tipoDados', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='serieextensa',
            name='tipoDadosID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidroSite.TipoDados'),
        ),
        migrations.AddField(
            model_name='qualidade',
            name='testeAderenciaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidroSite.TesteAderencia'),
        ),
    ]
